In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([
    [3, -1],
    [1, 3],
    [1, 1]
], dtype=float)
A

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

### Найти сингулярное разложение матрицы. Проверить, что А=UΣVᵀ.

![](/home/zorinep/big_data_magistracy/math/asserts/svd_notes.png)

In [25]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)  
Sigma = np.diag(s)

In [26]:
# матрица левых сингулярных векторов
U

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -2.06937879e-16]])

In [27]:
# сингулярные числа 
s

array([3.46410162, 3.16227766])

In [28]:
# диагональная матрица
Sigma

array([[3.46410162, 0.        ],
       [0.        , 3.16227766]])

In [29]:
# правые сингулярные векторы
Vt

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

![](/home/zorinep/big_data_magistracy/math/asserts/svd.png)

In [12]:
U @ Sigma @ Vt

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

Норма разности ||A - UΣV^T|| 

In [19]:
reconstruction_error = np.linalg.norm(A - A_reconstructed) 
reconstruction_error

np.float64(1.355199909595506e-15)

In [52]:
0.0000000000000014 > 1.355199909595506e-15

True

In [21]:
rank = np.linalg.matrix_rank(A)
rank

np.int64(2)

### Придумать вектор b, и решить систему Ax=b с помощью сингулярного разложения матрицы А

In [24]:
b = np.array([1.0, 2.0, 3.0])

In [ ]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)

In [53]:
Sigma = np.diag(s)

In [54]:
Sigma_plus = np.diag([1/si for si in s])  # псевдообратная
A_pinv = Vt.T @ Sigma_plus @ U.T
x = A_pinv @ np.array([1., 2., 3.])

In [55]:
print("x =", x)

x = [0.66666667 0.66666667]


In [56]:
print("Невязка r = A x - b =", A @ x - np.array([1.,2.,3.]))

Невязка r = A x - b = [ 0.33333333  0.66666667 -1.66666667]


In [57]:
print("||r|| =", np.linalg.norm(A @ x - np.array([1.,2.,3.])))

||r|| = 1.8257418583505538


### Выводы
матрица 𝐴 имеет ранг 2 (столбцов 2), система переопределённая — точного решения для выбранного b нет 
найдено наилучшее в смысле наименьших квадратов псевдорешение.

Берём 𝑏 из столбцового пространства 𝐴, тогда невязка будет ноль.

$$ 
b = A \begin{bmatrix} 1 \\ 2 \end{bmatrix}
  = \begin{bmatrix}
      3 \cdot 1 - 1 \cdot 2 \\
      1 \cdot 1 + 3 \cdot 2 \\
      1 \cdot 1 + 1 \cdot 2
    \end{bmatrix}
  = \begin{bmatrix} 1 \\ 7 \\ 3 \end{bmatrix}.
$$

In [72]:
b = np.array([1., 7., 3.])  # b = A @ [1,2]

In [73]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)
Sigma_plus = np.diag(1.0 / s)           
A_pinv = Vt.T @ Sigma_plus @ U.T

x = A_pinv @ b

In [74]:
print("x =", x)

x = [1. 2.]


In [77]:
print("Невязка r = A @ x - b =", A @ x - b)

Невязка r = A @ x - b = [-2.22044605e-16 -1.77635684e-15 -8.88178420e-16]


In [76]:
print("||r|| =", np.linalg.norm(A @ x - b))

||r|| = 1.9984014443252818e-15
